// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIMarketplaceApp.Models
{
    public partial class Famille
    {
        public Famille()
        {
            SousFamilles = new HashSet<SousFamille>();
        }

        public string IdFamille { get; set; }
        public string NomFamille { get; set; }

        public virtual ICollection<SousFamille> SousFamilles { get; set; }
    }
}