// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIMarketplaceApp.Models
{
    public partial class PrixProduit
    {
        public int IdPrix { get; set; }
        public string Prix { get; set; }
        public DateTime Date { get; set; }
        public string Url { get; set; }
    }
}