// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIMarketplaceApp.Models
{
    public partial class Produit
    {
        public string Reference { get; set; }
        public string Description { get; set; }
        public string Stock { get; set; }
        public int IdPrix { get; set; }
        public string IdMagasin { get; set; }
        public string IdSousFamille { get; set; }
        public string Photo { get; set; }

        public virtual Magasin IdMagasinNavigation { get; set; }
        public virtual PrixProduit IdPrixNavigation { get; set; }
        public virtual SousFamille IdSousFamilleNavigation { get; set; }
    }
}