// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace APIMarketplaceApp.Models
{
    public partial class ProduitSimilairesResult
    {
        public string Reference { get; set; }
        public string Description { get; set; }
        public string Stock { get; set; }
        public string prix { get; set; }
        public string Nom_magasin { get; set; }
        public string Photo { get; set; }
        public string Nom_sous_famille { get; set; }
    }
}
