// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIMarketplaceApp.Models
{
    public partial class SousFamille
    {
        public string IdSousFamille { get; set; }
        public string NomSousFamille { get; set; }
        public string IdFamille { get; set; }

        public virtual Famille IdFamilleNavigation { get; set; }
    }
}