// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIMarketplaceApp.Models
{
    public partial class Utilisateur
    {
        public string IdUser { get; set; }
        public string Email { get; set; }
    }
}